[package]
name = "fantasia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.14.1"
anyhow = "1.0"
clap = "4.0.23"
eframe = "0.19.0"
tracing-subscriber = "0.3"